### ISSUE TITLE
Colocar livro na web

### ISSUE THREAD

**Issue by damorim** [damorimRG/practical_testing_book#1]
Veja instruções do Jupyter Book sobre como colocar livro na web usando GitHub Pages. Pelo que entendi da nossa conversa hoje basta (1) criar uma branch (com nome especial), (2) ativar algo no GitHub para enxergar esta branch, e (3) criar um script simples para fazer deploy da branch master onde está o material do livro para tal branch (onde estará o HTML). Suponho que depois disto a pasta _build poderia ser retirada da branch master (eu acho).

**Comment by galilasmb** [comment]
Professor, não tenho permissão para editar as configurações do repositório, senão poderia fazer isto.

**Comment by damorim** [comment]
Vou dar permissão provisoriamente.

**Comment by galilasmb** [comment]
![image](https://user-images.githubusercontent.com/7373296/87092040-20dfec80-c211-11ea-8022-d52c1fdcf044.png)

**Comment by galilasmb** [comment]
Ocorreu o seguinte erro: 

Your site is having problems building: The variable {{ACM} on line 30 in references.bib was not properly closed with }}. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated.

**Comment by damorim** [comment]
Galileu, aparentemente este problema foi resolvido (era algo bem simples).
Vc. tem certeza que não é necessário fazer algo a mais? Pelo que alguém
disse hoje, seria necessário criar uma branch separada para o site e jogar
o conteúdo lá (o que está abaixo de _build). Por sinal, note que não
estamos usando o jekyll.

Marcelo

**Comment by galilasmb** [comment]
Utilizei Jekyll. Foi um pouco diferente. Talvez seja melhor deixar pra um grupo que fez com Jupyter realizar este procedimento, receio e bagunçar o repositório.

**Comment by galilasmb** [comment]
O que me diz, professor?

Se não me engano edenalsant que falou desse processo.

**Comment by galilasmb** [comment]
![image](https://user-images.githubusercontent.com/7373296/87105286-e423ed80-c230-11ea-896f-c0cdfa23ef22.png)

Tentei em um repositório separado e ficou assim. Talvez esteja faltando alguma configuração.

**Comment by galilasmb** [comment]
Feito, professor. Coloquei um readme para na hora do build atualizar o site.

**Comment by galilasmb** [comment]
Creio que possa até excluir a pasta _build. Porem ao executar o build, é necessário subir as atualizações com o comando que coloquei no README.

**Comment by galilasmb** [comment]
Posso alterar o build pra fazer isso de forma automática? @damorim

**Comment by damorim** [comment]
Sim
