### ISSUE TITLE
Notebook code has no file extension metadata

### ISSUE THREAD

**Issue by ViniciusSiqueira54** [damorimRG/practical_testing_book#14]
**Descrição:**
Ao _buildar_ o livro os seguintes _WARNINGs_ estão sendo disparados:

```
/home/siqueira/practical_testing_book/testgeneration/combinatorial.ipynb: WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
/home/siqueira/practical_testing_book/testgeneration/propertybased.ipynb: WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
```

**Resultado atual:** 
_WARNINGs_ relacionados a extensão dos arquivos `.ipynb` estão sendo exibidos durante a construção do livro

**Resultado esperado:**
_WARNINGs_ relacionados a extensão dos arquivos `.ipynb` não deveriam ser disparados

**Nota:** Outros capítulos que utilizam esse mesmo formato de arquivo não disparam esses _WARNINGs_

**Comment by ViniciusSiqueira54** [comment]
Pessoal consegui resolver esses warnings atualizando alguns dos metadatas dos arquivos de vcs, e limpando os outputs das celulas de vcs. 

Vcs precisam exibir esses outputs pro entendimento dos capitulos de vcs? Caso positivo tenho um backup aqui dos arquivos de vcs e posso desfazer as alterações.

**Comment by rafaelmotaalves** [comment]
@ViniciusSiqueira54 precisamos sim dos outputs do código, afinal esse é o objetivo de usar o python notebook certo? Além disso alguma das suas mudanças fizeram o build automático parar de funcionar, como você pode ver aqui: https://github.com/damorimRG/practical_testing_book/runs/936070273

você poderia por favor voltar as alterações?

**Comment by ViniciusSiqueira54** [comment]
@rafaelmotaalves posso sim, sem problemas. 

Não tenho certeza quanto a utilização do jupyter se é pra isso, pelo que entendi seria pra o leitor utilizar e ele mesmo criar os outputs dele, mas dai não tenho certeza se o objetivo é esse mesmo, enfim. 

Essa questão do build automático eu acho que ta quebrado de antes, @fehaa relatou que teve problemas com ele também, mesmo antes dessa alteração, toda vez que buildo e faço o deploy ele da algum erro, postamos até lá no classroom.

**Comment by rafaelmotaalves** [comment]
ok @ViniciusSiqueira54 , sobre o problema de build me parece que tem a ver com a versão do jupyter-book, você poderia ver se você está usando a mesma versão do script? Caso não, podemos atualizar o script para usar essa versão.

**Comment by ViniciusSiqueira54** [comment]
@rafaelmotaalves eles lançaram duas releases novas esses dias, se tiver como tu atualizar seria uma boa. :)

**Comment by rafaelmotaalves** [comment]
Pronto, está atualizado

**Comment by ViniciusSiqueira54** [comment]
Valeu @rafaelmotaalves , voltei o arquivo de backup do `combinatorial.ipynb` pro repositório. Obrigado pelo Help com o script de build.

**Comment by rafaelmotaalves** [comment]
Obrigado @ViniciusSiqueira54 !

**Comment by gabritto** [comment]
@ViniciusSiqueira54 preciso do output no arquivo `propertybased.ipynb` também, se puder desfazer a alteração agradeço.

**Comment by ViniciusSiqueira54** [comment]
Oi @gabritto, desculpa a demora no retorno, ótimo então.. Sendo assim podemos considerar esse issue fix.
