### ISSUE TITLE
Remove Example of a flaky test section to delete duplicate code

### ISSUE THREAD

**Issue by GeraldoMGN** [damorimRG/practical_testing_book#28]
[Flaky test](https://damorimrg.github.io/practical_testing_book/testregression/flakytests.html)

Both the "Example of a flaky test section" and the "Hands On" section contains the same code as example. We can remove the "Example of a flaky test section" since this breaks a couple of our rules:
- The chapter becomes too long.
- The "Hands On" section isn't in the beginning.

Removing the section and moving the Google Colab up in the page should fix these problems. Some text from the section would have to be moved the Colab.

**Comment by GeraldoMGN** [comment]
To be solved in #32.

**Comment by Diogodhs** [comment]
The other thing I realized is that the quiz section could be used on the same page, without having to open a new browser page, as other pages in this book have it.
