### ISSUE TITLE
[Revision] Mutation Testing

### ISSUE THREAD

**Issue by GeraldoMGN** [damorimRG/practical_testing_book#33]
[Mutation Testing](https://damorimrg.github.io/practical_testing_book/testadequacy/mutation.html) revision reserved by @GeraldoMGN

**Comment by AndersonPJ** [comment]
@GeraldoMGN O que acha de mover 'Mutation Operators' para antes de 'Examples'? Também se tiver uma forma de colocar 'Pros' e 'Cons' lado a lado ficaria mais fácil de comparar.

**Comment by GeraldoMGN** [comment]
@AndersonPJ Movi 'Mutation Operators' para cima e acabei por transformar 'Pros' e 'Cons' na seção 'Final considerations' para seguir melhor nossos regras.

**Comment by AndersonPJ** [comment]
@GeraldoMGN Creio que uma pequena padronização na forma que se cria as 'Notas' na parte prática e uma revisão geral do texto (começar paragrafo com letra maiúscula; terminar com ponto final e etc) sejam o que falta.

Ambas são atividades relativas ao texto em si, então não são obrigatórias nesse momento, mas eu creio que seja interessante deixar o lembrete aqui para referência futura.

**Comment by GeraldoMGN** [comment]
### Changes made:

- Convert the Mutation Testing file from a .md file to a .ipynb to add more interactivity (i.e. Videos)
- Overall readability improvement and typo correction
- Add a video
- Move "Hands On" section to beginning of the chapter
- Remove "Examples of Operators Used" section: Too long and it's content didn't had much useful content
- Remove "Background" section since it had the same information compared to the references. This section appears to be a "filler", existing only to mark the references.
- Transformed the "Pros and Cons" section int the "Final Considerations" one.

**Comment by GeraldoMGN** [comment]
### Notes:

- We will need to expand on the "Final considerations" section when we get to the content revision.
- We could add a quiz to this section in the future.

**Comment by damorim** [comment]
Thanks for this.

Comment:

* Use a single ipynb file for everything. At "Hands On" show the link to collab. Avoid duplicate content.
