### ISSUE TITLE
[Revision] Build Systems

### ISSUE THREAD

**Issue by AndersonPJ** [damorimRG/practical_testing_book#34]
[Build Systems](https://damorimrg.github.io/practical_testing_book/testregression/buildsystems.html) reserved by @AndersonPJ

**Comment by GeraldoMGN** [comment]
@AndersonPJ Tem alguns erros ortográficos no texto, por exemplo, no terceiro parágrafo de Build Systems "its extremely versatility.", deveria ser "its extreme versatility.". Um modo muito rápido que eu achei para corrigir essas coisa é colar o texto no Google Docs e usar o corretor dele.
