### ISSUE TITLE
[Revision] Unit Testing

### ISSUE THREAD

**Issue by bcgs** [damorimRG/practical_testing_book#35]

**Comment by damorim** [comment]
Oi Bruno, a seção está bem melhor que antes. Ainda vejo inconsistências entre o que o que é apresentado no Jupyter Book (aberto no livro) e no *notebook*, aberto no Colab. Olhando para os exemplos dos alunos percebi que o que eles fizeram para resolver o problema foi criar apenas um arquivo .ipynb para resolver qualquer possibilidade de inconsitências. Sugiro vc. fazer o mesmo.

**Comment by bcgs** [comment]
Feito. Espero que esteja correto.
