### ISSUE TITLE
[Revision] Acceptance Testing

### ISSUE THREAD

**Issue by Diogodhs** [damorimRG/practical_testing_book#36]
Possibles improvements:
- To use the same word to refer client/customer. I would use "client" because of the figure that was shown at the beginning. (if the second picture isn't deleted)
- The first picture must be removed due to the many characters that the user may not immediately understand.
- Maybe to delete the second picture too because there is no explanation for it.
- There are many text, so we must summarize it.
- There is no “Open in Colab” icon in the "Hand's on" section and this section is on the third scrolling page, not the first.
- To use some short video explaining the section at the beginning.

**Comment by Diogodhs** [comment]
I put some possible improvements in the description.

**Comment by Diogodhs** [comment]
I added and edited the description with some others possible improvements:

- To use the same word to refer client/customer. I would use "client" because of the figure that was shown at the beginning. (if the second picture isn't deleted)
- The first picture must be removed due to the many characters that the user may not immediately understand.
- Maybe to delete the second picture too because there is no explanation for it.
- There are many text, so we must summarize it.
- To use some short video explaining the section at the beginning.

**Comment by damorim** [comment]
@Diogodhs,

**Comment by damorim** [comment]
@Diogodhs, 

bom progresso.

Comentário:

O arquivo .ipynb que vc. adicionou é um único bloco de código! Isto (1) está fora do padrão, (2) não ajuda o usuário a praticar, e (3) está com conteúdo redundante (e diferente do que é mostrado no .md).

Por favor, use **um único** arquivo .ipynb com o texto e os blocos de código (não é necessário ter um arquivo .md). Desta forma, (1) vc. garante que é o mesmo código/texto que será usado no collab e na leitura, (2) vc. explica cada passo da execução. Observe que vc. pode usar markdown dentro do arquivo ipynb.

Veja exemplos no repositório de como fazer isto, se estiver em dúvida.

**Comment by Diogodhs** [comment]
@damorim 

Certo, vou retirar o .ipynb extra que criei e referenciar o "open in colab" para ele próprio.
