### ISSUE TITLE
[Revision] Fuzzing Testing

### ISSUE THREAD

**Issue by LeonardoGaldino** [damorimRG/practical_testing_book#40]
Review **Fuzzing** subsection structure under **Test generation** in [the book website](https://damorimrg.github.io/practical_testing_book/) according to [these structural rules](https://docs.google.com/document/d/1-osbMfkbkMK0OWfcYSOJfVA9DwENFSaM9JbsCnXBxmU/edit).

**Comment by bcgs** [comment]
Already in progress... #33

**Comment by LeonardoGaldino** [comment]
Updated issue with a different topic and removed duplicate label. Thanks for pointing that out.

**Comment by damorim** [comment]
Good job!

Please make sure you are not copying text from anywhere. I could be in real trouble if you do this! For example, I was a bit skeptical after reading the sentence below:

"As seen in our example, fuzzers are very easy to use and even develop. I encourage you to take a look into pythonfuzz’s repository and see how simple the implementation really is. "
