### ISSUE TITLE
[Revision] Combinatorial Testing

### ISSUE THREAD

**Issue by ahlp** [damorimRG/practical_testing_book#42]
Review Combinatorial Testing:
https://damorimrg.github.io/practical_testing_book/testgeneration/combinatorial.html

**Comment by ahlp** [comment]
- O HandsOn esta complicado, inclusive com coisas sobre ambiente do python
- O HandsOn n tem link pro colab
- O exercise poderia ter uma explicação para dar dicas (e legal ter um, mas se a pessoa ficar perdida nao tem mt oq fazer)
- Nao achei nenhum video curto sobre o assunto 😞

**Comment by Diogodhs** [comment]
Outras coisas que eu acrescentaria:
- Texto muito grande, precisa ser resumido.
- HandsOn está meio longe do início. 

Lembro do professor falar que parte do texto poderia ficar no final, como informação extra.

**Comment by damorim** [comment]
Tente resumir um pouco mais este texto inicial.
