### ISSUE TITLE
[Revision] Structural Testing

### ISSUE THREAD

**Issue by pamella** [damorimRG/practical_testing_book#44]
**Section to be reviewed:**
https://damorimrg.github.io/practical_testing_book/testadequacy/coverage.html

**Comment by damorim** [comment]
- Revise the sentence below:

" quality of suite testing of program structures. There are three techniques addressed to this kind of test."
->
" quality of test suites based on the structure of the code. There popular approaches to structure testing are:"

- Please add a simple link to Google Colab as others are using. No need to add that sentence before. Try to use the same format.
- It is a bit surprising this package does not have support for branch coverage. Please check. If it does, add something about it.
- Run in your computer section seems unnecessary. It should be obvious from the notebook. That is why we are using it.
- On References, please add a short sentence on each of these. The reader should know what to expect when clicking on the link.
