### ISSUE TITLE
Create a test case to check if changes are valid

### ISSUE THREAD

**Issue by damorim** [damorimRG/practical_testing_book#5]
Please write a test case to validate results of the build script.

Some students are adding material and not checking if the page can be build.

Lots of warnings:

===
reading sources... [100%] testregression/selectionprio                          
WARNING: Found a content page that is not in _toc.yml: fundamentals/README.md.
/home/damorim/projects/practical_testing_book/mocking/basics.md:1: WARNING: Non-consecutive header level increase; 0 to 3
/home/damorim/projects/practical_testing_book/mocking/notebook.ipynb:20002: WARNING: Non-consecutive header level increase; 1 to 3
/home/damorim/projects/practical_testing_book/testadequacy/coverage.ipynb:20002: WARNING: Non-consecutive header level increase; 1 to 3
/home/damorim/projects/practical_testing_book/testgeneration/propertybased.ipynb: WARNING: Notebook code has no file extension metadata, defaulting to `.txt`
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:1: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:6: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:10: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:77: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:114: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:119: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/buildsystems.md:126: WARNING: Non-consecutive header level increase; 0 to 2
/home/damorim/projects/practical_testing_book/testregression/continuousintegration.md:1: WARNING: Non-consecutive header level increase; 0 to 4
/home/damorim/projects/practical_testing_book/testregression/continuousintegration.md:5: WARNING: Non-consecutive header level increase; 4 to 6
/home/damorim/projects/practical_testing_book/testregression/continuousintegration.md:9: WARNING: Non-consecutive header level increase; 4 to 6
/home/damorim/projects/practical_testing_book/testregression/continuousintegration.md:14: WARNING: Non-consecutive header level increase; 4 to 6
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/damorim/projects/practical_testing_book/fundamentals/README.md: WARNING: document isn't included in any toctree
done
===

This is what I see now. 

Suggest to write a test to check if errors/warnings are present. 

We could use that test with Travis.

Marcelo

**Comment by rafaelmotaalves** [comment]
I can try to do this with Github Actions @damorim
